version: "3.8"
services:
  web:
    build: ./src
    restart: always
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://sn41:sn41@db:5432/hwdb_dev
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=sn41
      - POSTGRES_PASSWORD=sn41
      - POSTGRES_DB=hwdb_dev
    restart: always
volumes:
  postgres_data: